import PDFDocument from 'pdfkit'

// pdfkit builds PDFs by streaming draw commands, not by rendering a DOM —
// pure JS, no headless-browser process. Deliberately chosen over a
// Puppeteer/Playwright HTML-to-PDF approach: this backend runs on Render's
// free tier, which is already showing memory/connection strain, and a
// headless Chrome process per export is a realistic OOM risk there. Less
// visual flexibility, but nothing here needs more than a branded header and
// a table.

const BRAND = {
  navy: '#0A2342',
  gold: '#C9973A',
  textDark: '#1f2937',
  textMuted: '#6b7280',
  border: '#e5e7eb',
  stripe: '#f9fafb',
}

const PAGE_MARGIN = 40
const ROW_HEIGHT = 22
const HEADER_ROW_HEIGHT = 24
const HEADER_BAND_HEIGHT = 90

// generateReportPDF({ title, subtitle, columns, rows, generatedAt }) -> Promise<Buffer>
// columns: [{ key, label, align? }]   rows: [{ [key]: string|number }]
export function generateReportPDF({ title, subtitle, columns, rows, generatedAt = new Date() }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4', bufferPages: true })
    const chunks = []
    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    drawHeader(doc, title, subtitle)
    drawTable(doc, columns, rows)
    stampFooterOnEveryPage(doc, generatedAt)

    doc.end()
  })
}

function drawHeader(doc, title, subtitle) {
  const pageWidth = doc.page.width
  const contentWidth = pageWidth - PAGE_MARGIN * 2

  doc.rect(0, 0, pageWidth, HEADER_BAND_HEIGHT).fill(BRAND.navy)

  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(13)
    .text('UGANDA AIR CARGO CORPORATION', PAGE_MARGIN, 22, { align: 'center', width: contentWidth })

  doc.fillColor(BRAND.gold).font('Helvetica-Bold').fontSize(17)
    .text(title, PAGE_MARGIN, 42, { align: 'center', width: contentWidth })

  if (subtitle) {
    doc.fillColor('#cbd5e1').font('Helvetica').fontSize(9)
      .text(subtitle, PAGE_MARGIN, 68, { align: 'center', width: contentWidth })
  }

  doc.fillColor(BRAND.textDark)
  doc.y = HEADER_BAND_HEIGHT + 20
}

function drawTable(doc, columns, rows) {
  const usableWidth = doc.page.width - PAGE_MARGIN * 2
  const colWidth = usableWidth / columns.length
  const pageBottom = doc.page.height - PAGE_MARGIN - 20 // leave room for the footer stamp

  const drawHeaderRow = () => {
    const y = doc.y
    doc.rect(PAGE_MARGIN, y, usableWidth, HEADER_ROW_HEIGHT).fill(BRAND.gold)
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(9)
    columns.forEach((col, i) => {
      doc.text(col.label, PAGE_MARGIN + i * colWidth + 6, y + 7, {
        width: colWidth - 12,
        align: col.align || 'left',
      })
    })
    doc.y = y + HEADER_ROW_HEIGHT
    doc.fillColor(BRAND.textDark).font('Helvetica').fontSize(9)
  }

  drawHeaderRow()

  if (rows.length === 0) {
    doc.fillColor(BRAND.textMuted).font('Helvetica').fontSize(10)
      .text('No data available for the selected range.', PAGE_MARGIN, doc.y + 12)
    return
  }

  rows.forEach((row, idx) => {
    if (doc.y + ROW_HEIGHT > pageBottom) {
      doc.addPage()
      doc.y = PAGE_MARGIN
      drawHeaderRow()
    }

    const y = doc.y
    if (idx % 2 === 1) {
      doc.rect(PAGE_MARGIN, y, usableWidth, ROW_HEIGHT).fill(BRAND.stripe)
    }
    doc.fillColor(BRAND.textDark).font('Helvetica').fontSize(9)
    columns.forEach((col, i) => {
      const value = row[col.key]
      doc.text(value === null || value === undefined ? '—' : String(value), PAGE_MARGIN + i * colWidth + 6, y + 6, {
        width: colWidth - 12,
        align: col.align || 'left',
      })
    })
    doc.y = y + ROW_HEIGHT
    doc.moveTo(PAGE_MARGIN, doc.y).lineTo(PAGE_MARGIN + usableWidth, doc.y)
      .strokeColor(BRAND.border).lineWidth(0.5).stroke()
  })
}

function stampFooterOnEveryPage(doc, generatedAt) {
  const stamp = `Generated by DIMS v1.0 · Confidential · Internal Use Only · ${generatedAt.toLocaleString('en-UG', { dateStyle: 'medium', timeStyle: 'short' })}`
  const range = doc.bufferedPageRange()
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i)
    const bottom = doc.page.height - 30
    doc.fontSize(8).fillColor(BRAND.textMuted).font('Helvetica')
      .text(stamp, PAGE_MARGIN, bottom, { align: 'center', width: doc.page.width - PAGE_MARGIN * 2 })
  }
}
